project_id = "sxmkrmidebylykaefmsl"

[functions.firecrawl-scrape]
verify_jwt = false

[functions.get-subscriber]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
