project_id = "sxmkrmidebylykaefmsl"

[functions.firecrawl-scrape]
verify_jwt = false

[functions.get-subscriber]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.auto-generate-invoices]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.reset-password-with-otp]
verify_jwt = false

[functions.map-data]
verify_jwt = false

[functions.update-technician-location]
verify_jwt = false
